'''
Created on Aug 15, 2019

@author: foobar
'''

APP_NAME = "ADGL"
SSH_DELAY = "SSH_DELAY"
MTR_DELAY = "MTR_DELAY"
TOOL_ROOT = "GLV_TOOL_ROOT"
NODES_LIST = "nodes_list"
PHASE = "ADGLV_PHASE"
LOG_FILE_PATH = "ADGLV_LOG_FILE_PATH"
MONGO_HOST = "ADGLV_MONGO_HOST"
MONGO_PORT = "ADGLV_MONGO_PORT"
NODE_NAME = "ADGLV_NODE_NAME"

# phases
PHASE_DATA_COLLECTION = "DATA_COLLECTION"
PHASE_FEAT_GENERATION = "FEAT_GENERATION"
PHASE_TRAIN_MODEL = "TRAIN_MODEL"
PHASE_PREDICTION = "PREDICTION"
PHASE_FEAT_TRAIN = "FEAT_TRAIN"
PHASE_FEAT_PREDICT = "FEAT_PREDICT"
PHASE_FTP = "FTP"
PHASE_DATA_VIZ = "DATA_VIZ"

# Data collection
# in seconds
DATA_COLLECTION_INTERVAL = "ADGLV_DATA_COLLECTION_INTERVAL"
# in YYYY-MM-DD HH:MM:SS format
DATA_END_TIME = "ADGLV_DATA_END_TIME"
RABBITMQ_HOST = "ADGLV_RABBITMQ_HOST"
NODES_PRIVATE_KEY = "ADGLV_NODES_PRIVATE_KEY"
NODES_PRIVATE_KEY_PASSPHRASE = "ADGLV_NODES_PRIVATE_KEY_PASSPHRASE"
NODES_YAML_PATH = "ADGLV_NODES_YAML_PATH"
THREAD_COUNT = "ADGLV_THREAD_COUNT"
RELAYED_NODES = "ADGLV_RELAYED_NODES"
RELAYED_NODES_PORT = "ADGLV_RELAYED_NODES_PORT"
DATABASE_NAME = "ADGLV_DATABASE_NAME"
COLLECTION_NAME = "ADGLV_COLLECTION_NAME"

# Feature vector generation
FEATURE_DATA_START = "ADGLV_FEATURE_DATA_START"
FEATURE_DATA_END = "ADGLV_FEATURE_DATA_END"
FEATURE_CSV_DIR = "ADGLV_FEATURE_CSV_DIR"
# both values should sum up to 1 (if using)
FEATURE_DATASET_UPPER_CUT_OFF = "ADGLV_FEATURE_DATASET_UPPER_CUT_OFF"
FEATURE_DATASET_LOWER_CUT_OFF = "ADGLV_FEATURE_DATASET_LOWER_CUT_OFF"

# Visualization configuration
VIZ_SAVE_DIR = "ADGLV_VIZ_SAVE_DIR"

# TRAINING CONFIGURATION
TRAIN_ROOT_DIR = "ADGLV_TRAIN_ROOT_DIR"
TRAIN_MODEL_DIR = "ADGLV_TRAIN_MODEL_DIR"
TRAIN_DATASET_TRAINING_RATIO = "ADGLV_TRAIN_DATASET_TRAINING_RATIO"
TRAIN_LEARNING_RATE = "ADGLV_TRAIN_LEARNING_RATE"
TRAIN_STEPS = "ADGLV_TRAIN_STEPS"
TRAIN_BATCH_SIZE = "ADGLV_TRAIN_BATCH_SIZE"
TRAIN_HIDDEN_UNITS = "ADGLV_TRAIN_HIDDEN_UNITS"
TRAIN_PERIODS = "ADGLV_TRAIN_PERIODS"

# PREDICTION CONFIGURATION
PREDICT_ROOT_DIR = "ADGLV_PREDICT_ROOT_DIR"
PREDICT_DATASET_PREDICTION_RATIO = "ADGLV_PREDICT_DATASET_PREDICTION_RATIO"
