'''
Created on Aug 15, 2019

@author: foobar
'''

APP_NAME = "ADGL"
SSH_DELAY = "SSH_DELAY"
MTR_DELAY = "MTR_DELAY"
TOOL_ROOT = "GLV_TOOL_ROOT"
NODES_LIST = "nodes_list"


DATA_COLLECTION_INTERVAL = "ADGLV_DATA_COLLECTION_INTERVAL"
DATA_END_TIME = "ADGLV_DATA_END_TIME"
MONGO_HOST = "ADGLV_MONGO_HOST"
MONGO_PORT = "ADGLV_MONGO_PORT"
RABBITMQ_HOST = "ADGLV_RABBITMQ_HOST"
NODE_NAME = "ADGLV_NODE_NAME"
NODES_PRIVATE_KEY = "ADGLV_NODES_PRIVATE_KEY"
NODES_PRIVATE_KEY_PASSPHRASE = "ADGLV_NODES_PRIVATE_KEY_PASSPHRASE"
NODES_YAML_PATH = "ADGLV_NODES_YAML_PATH"
THREAD_COUNT = "ADGLV_THREAD_COUNT"
LOG_FILE_PATH = "ADGLV_LOG_FILE_PATH"
